import { Hotel } from "../../models/Hotel";

const hotels: Hotel[] = [
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒", "臭"],
    Advantage: ["乾淨", "香"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
  {
    _id: "1",
    Name: "大倉久和大飯店 (The Okura Prestige Taipei Hotel)",
    County: "台北市",
    District: "中山區",
    Disadvantage: ["髒"],
    Advantage: ["乾淨"],
    Keyword: "九河",
    Sentiment: "123",
  },
];

export default hotels;
